//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ehrmsupLocalEntities : DbContext
    {
        public ehrmsupLocalEntities()
            : base("name=ehrmsupLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpLeaveHistory> EmpLeaveHistories { get; set; }
        public virtual DbSet<emppersonal> emppersonals { get; set; }
        public virtual DbSet<mAwardDetail> mAwardDetails { get; set; }
        public virtual DbSet<mBloodGroup> mBloodGroups { get; set; }
        public virtual DbSet<mBloodGroupMaster> mBloodGroupMasters { get; set; }
        public virtual DbSet<mbranchMaster> mbranchMasters { get; set; }
        public virtual DbSet<mCategoryMaster> mCategoryMasters { get; set; }
        public virtual DbSet<mClassMaster> mClassMasters { get; set; }
        public virtual DbSet<mdeptmaster> mdeptmasters { get; set; }
        public virtual DbSet<mdesigmast> mdesigmasts { get; set; }
        public virtual DbSet<mFWblkma> mFWblkmas { get; set; }
        public virtual DbSet<mFWdisma> mFWdismas { get; set; }
        public virtual DbSet<mFWpanma> mFWpanmas { get; set; }
        public virtual DbSet<mLeaveType> mLeaveTypes { get; set; }
        public virtual DbSet<mLoanType> mLoanTypes { get; set; }
        public virtual DbSet<mMaritalStatu> mMaritalStatus { get; set; }
        public virtual DbSet<mMaritalStatusMaster> mMaritalStatusMasters { get; set; }
        public virtual DbSet<mOfficeLevel> mOfficeLevels { get; set; }
        public virtual DbSet<mofficemaster> mofficemasters { get; set; }
        public virtual DbSet<mofficemasterForReport> mofficemasterForReports { get; set; }
        public virtual DbSet<mOfficeType> mOfficeTypes { get; set; }
        public virtual DbSet<mOrderType> mOrderTypes { get; set; }
        public virtual DbSet<mpiscadremast> mpiscadremasts { get; set; }
        public virtual DbSet<mpisemptype> mpisemptypes { get; set; }
        public virtual DbSet<mquali> mqualis { get; set; }
        public virtual DbSet<mquali_29_Dec_2020> mquali_29_Dec_2020 { get; set; }
        public virtual DbSet<mqualilevel> mqualilevels { get; set; }
        public virtual DbSet<mRelationMaster> mRelationMasters { get; set; }
        public virtual DbSet<mReligionTypeMaster> mReligionTypeMasters { get; set; }
        public virtual DbSet<mState> mStates { get; set; }
        public virtual DbSet<mstatemaster> mstatemasters { get; set; }
        public virtual DbSet<mStateServiceGradingMaster> mStateServiceGradingMasters { get; set; }
        public virtual DbSet<mStateServiceMaster> mStateServiceMasters { get; set; }
        public virtual DbSet<mSubCategoryMaster> mSubCategoryMasters { get; set; }
        public virtual DbSet<pisawarddetail> pisawarddetails { get; set; }
        public virtual DbSet<pisempaddress> pisempaddresses { get; set; }
        public virtual DbSet<pisempdepproceed> pisempdepproceeds { get; set; }
        public virtual DbSet<pisempeducation> pisempeducations { get; set; }
        public virtual DbSet<pisempfamily> pisempfamilies { get; set; }
        public virtual DbSet<pisemphistory> pisemphistories { get; set; }
        public virtual DbSet<pisempjoinrelievedetail> pisempjoinrelievedetails { get; set; }
        public virtual DbSet<pisempleave> pisempleaves { get; set; }
        public virtual DbSet<pisempnominee> pisempnominees { get; set; }
        public virtual DbSet<pisempprofessional> pisempprofessionals { get; set; }
        public virtual DbSet<pisemptraining> pisemptrainings { get; set; }
        public virtual DbSet<pisloandetail> pisloandetails { get; set; }
        public virtual DbSet<pistransferlist> pistransferlists { get; set; }
        public virtual DbSet<pistransferorderauthority> pistransferorderauthorities { get; set; }
        public virtual DbSet<msubquali> msubqualis { get; set; }
        public virtual DbSet<msubquali_29_Dec_2020> msubquali_29_Dec_2020 { get; set; }
        public virtual DbSet<pistransferemplist> pistransferemplists { get; set; }
        public virtual DbSet<PromotionDetail> PromotionDetails { get; set; }
        public static object Models { get; internal set; }
    }
}
