//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emppersonal
    {
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public Nullable<long> transid { get; set; }
        public Nullable<long> officeid { get; set; }
        public string EmpNameTitle { get; set; }
        public string empfname { get; set; }
        public string empmname { get; set; }
        public string emplname { get; set; }
        public string empnamelocal { get; set; }
        public string empname_mlocal { get; set; }
        public string empname_Llocal { get; set; }
        public Nullable<System.DateTime> empdob { get; set; }
        public string empfmh { get; set; }
        public string empfmhname { get; set; }
        public string empfhm_mname { get; set; }
        public string empfhm_lname { get; set; }
        public string empmarst { get; set; }
        public string empspouse { get; set; }
        public string empidmasrk { get; set; }
        public string empcaste { get; set; }
        public string empreligion { get; set; }
        public string empcategory { get; set; }
        public string emphmst { get; set; }
        public string emphmdist { get; set; }
        public string emphmtown { get; set; }
        public string esalarycd { get; set; }
        public string emphomeoff { get; set; }
        public string empmedcer { get; set; }
        public string empcharcer { get; set; }
        public byte[] empphoto { get; set; }
        public byte[] empfinger { get; set; }
        public string emprail { get; set; }
        public string empremark { get; set; }
        public string empgender { get; set; }
        public string empblood { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string empheight { get; set; }
        public string currdesig { get; set; }
        public string Subdesig_OLD { get; set; }
        public Nullable<System.DateTime> nextincrement { get; set; }
        public Nullable<System.DateTime> doeoffdesigincre { get; set; }
        public Nullable<int> cadre_cd { get; set; }
        public Nullable<int> branchcd { get; set; }
        public string postdeptid { get; set; }
        public string desigdescription { get; set; }
        public string estabdeptid { get; set; }
        public Nullable<long> estabofficeid { get; set; }
        public string policepinno { get; set; }
        public Nullable<System.DateTime> dofjoin { get; set; }
        public Nullable<System.DateTime> dofretirecurr { get; set; }
        public string modeofreccurr { get; set; }
        public string emptypecurr { get; set; }
        public Nullable<int> EmpProertyFileId { get; set; }
        public string UID { get; set; }
        public Nullable<int> ServiceCd { get; set; }
        public Nullable<int> GradingCd { get; set; }
        public Nullable<int> AppointmentCd { get; set; }
        public string StateCadre { get; set; }
        public string currentclass { get; set; }
        public string Gazetted { get; set; }
        public string DEuserid { get; set; }
        public Nullable<System.DateTime> DEdate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string verify { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
        public string IpAddress { get; set; }
        public string VALIDuserid { get; set; }
        public string stgpfcpstype { get; set; }
        public string gpfcpsnumber { get; set; }
        public string PayCommision { get; set; }
        public string PayScale { get; set; }
        public string PayBand { get; set; }
        public string GradePay { get; set; }
        public string BasicPay { get; set; }
        public string employeeexit { get; set; }
        public string Nationality { get; set; }
        public string SubCategory { get; set; }
        public string departmentalEmpCode { get; set; }
        public string parentdeptid { get; set; }
        public string TempEmpcd { get; set; }
        public Nullable<short> HealthStatusId { get; set; }
        public Nullable<long> mainestabofficeid { get; set; }
        public Nullable<long> Parentofficeid { get; set; }
        public Nullable<short> distcd { get; set; }
        public Nullable<System.DateTime> AppointmentDt { get; set; }
        public Nullable<System.DateTime> ServiceJoiningDt { get; set; }
        public string SeniorityNo { get; set; }
        public string joiningorder { get; set; }
        public Nullable<System.DateTime> joiningorderdate { get; set; }
        public Nullable<int> SpecialityId { get; set; }
        public Nullable<int> Subdesig { get; set; }
        public string CouncilRegistrationNo { get; set; }
        public Nullable<System.DateTime> CouncilRegistrationDt { get; set; }
    }
}
