//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbranchMaster
    {
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string officeid { get; set; }
        public int branchcd { get; set; }
        public string branchnm { get; set; }
        public string branchname_Local { get; set; }
        public string DEUserId { get; set; }
        public Nullable<System.DateTime> DEDate { get; set; }
        public string CIPAdd { get; set; }
        public string status { get; set; }
    }
}
