//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdeptmaster
    {
        public int StateId { get; set; }
        public string deptid { get; set; }
        public string deptabbr { get; set; }
        public string deptname { get; set; }
        public string deptname_hindi { get; set; }
        public byte[] deptphoto { get; set; }
        public string DeptConStr { get; set; }
        public Nullable<long> GriNumber { get; set; }
        public Nullable<System.DateTime> GriNumberUpdationDate { get; set; }
        public string LatestGriNumber { get; set; }
        public string enivaran { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public string eSamadhanNote { get; set; }
        public string eSamadhanOnline { get; set; }
        public string eSameekshaOnlineYN { get; set; }
        public Nullable<int> eSameekshaWorkCode { get; set; }
        public string deptabbrLocal { get; set; }
        public string eSameekshaWorkCodeYear { get; set; }
        public string DEUserId { get; set; }
        public System.DateTime DEDate { get; set; }
        public string CIPAdd { get; set; }
        public string Status { get; set; }
        public string EntityType { get; set; }
        public string estimatedStrength { get; set; }
        public Nullable<short> HeadDeptID { get; set; }
        public string HeadDeptName { get; set; }
        public string HeadDeptName_Local { get; set; }
    }
}
