//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdesigmast
    {
        public int StateId { get; set; }
        public int desigcode { get; set; }
        public string designame { get; set; }
        public string designame_Local { get; set; }
        public string desigabbr { get; set; }
        public string DEUserId { get; set; }
        public System.DateTime DEDate { get; set; }
        public string CIPAdd { get; set; }
        public string Status { get; set; }
        public string RetirementAge { get; set; }
        public string gazetted { get; set; }
        public string PayScaleGrade { get; set; }
        public string displayOrder { get; set; }
        public string DesigGroup { get; set; }
        public string DesigClass { get; set; }
        public string Status_Use { get; set; }
    }
}
