//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mFWdisma
    {
        public int StateId { get; set; }
        public string dis_code { get; set; }
        public string StateAbbr { get; set; }
        public string dis_name { get; set; }
        public string dis_namh { get; set; }
        public string tribal_nontribal { get; set; }
        public string Status { get; set; }
        public string DistrictClass { get; set; }
        public Nullable<int> DivisionCode { get; set; }
    }
}
