//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mFWpanma
    {
        public int StateId { get; set; }
        public string dis_code { get; set; }
        public string pan_code { get; set; }
        public string blk_code { get; set; }
        public string pan_name { get; set; }
        public string pan_nameh { get; set; }
        public string pan_type { get; set; }
        public string Status { get; set; }
    }
}
