//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mLeaveType
    {
        public int LeaveTypeID { get; set; }
        public string LeaveTypeName { get; set; }
        public string Status { get; set; }
        public int DisplayOrder { get; set; }
        public string ForWomenOnly { get; set; }
        public string AutoCreditable { get; set; }
        public string ForMenOnly { get; set; }
    }
}
