//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mOfficeLevel
    {
        public string StateId { get; set; }
        public string officelevel { get; set; }
        public string deptid { get; set; }
        public string officetype { get; set; }
        public string officetylocal { get; set; }
        public string status { get; set; }
    }
}
