//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mofficemaster
    {
        public int StateId { get; set; }
        public string deptid { get; set; }
        public long officeid { get; set; }
        public string officelevel { get; set; }
        public string officename { get; set; }
        public string officeaddr { get; set; }
        public string distcd { get; set; }
        public string urbrul { get; set; }
        public string tehsilcode { get; set; }
        public string blockcd { get; set; }
        public string panchcd { get; set; }
        public string concd { get; set; }
        public string desigcode { get; set; }
        public Nullable<long> reportoffice { get; set; }
        public string EmailId { get; set; }
        public string Wh_SSt { get; set; }
        public string officenamelocal { get; set; }
        public string officeaddresslocal { get; set; }
        public string NodalOfficerEmpCode { get; set; }
        public string grcellincharge { get; set; }
        public Nullable<byte> IsOnline { get; set; }
        public Nullable<byte> isgrcell { get; set; }
        public string grcellinchargedeptid { get; set; }
        public string DEuserid { get; set; }
        public Nullable<System.DateTime> DEdate { get; set; }
        public string CIPAdd { get; set; }
        public string officephone { get; set; }
        public string GenOffice { get; set; }
        public string mapoldofficeid { get; set; }
        public string mapnewofficeid { get; set; }
        public string officetype { get; set; }
        public string tribalAreaCode { get; set; }
        public string ddodemandcd { get; set; }
        public string treasurycd { get; set; }
        public string mobilenumber { get; set; }
        public string Status { get; set; }
        public string attachedoffice { get; set; }
        public string OfficeState { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string DepartmentalOfficeCode { get; set; }
    }
}
