//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mofficemasterForReport
    {
        public string deptid { get; set; }
        public string deptname { get; set; }
        public long officeid { get; set; }
        public string officelevel { get; set; }
        public string officename { get; set; }
        public Nullable<long> reportofficeid { get; set; }
        public string reportofficename { get; set; }
        public string OfficeState { get; set; }
        public string distcd { get; set; }
        public string dis_name { get; set; }
    }
}
