//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mOfficeType
    {
        public string DeptId { get; set; }
        public int OfficetypeId { get; set; }
        public string OfficeTypeName { get; set; }
        public string OfficeTypeName_Local { get; set; }
    }
}
