//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mOrderType
    {
        public int OrderType { get; set; }
        public string OrderName { get; set; }
        public string OrderDescription { get; set; }
        public string OrderBehaviour { get; set; }
        public string StateID { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string IpAddress { get; set; }
        public string Verify { get; set; }
        public string Entry_Type { get; set; }
        public string EmployeeExit { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<byte> EmployeeStatusKey { get; set; }
        public string FinancialChngFlag { get; set; }
    }
}
