//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpiscadremast
    {
        public int StateId { get; set; }
        public int Cadre_cd { get; set; }
        public string Cadre_nm { get; set; }
        public string cadre_abbr { get; set; }
        public string deptid { get; set; }
        public string Cadre_nmLocal { get; set; }
        public string Status { get; set; }
    }
}
