//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRelationMaster
    {
        public int StateId { get; set; }
        public int RelationId { get; set; }
        public string RelationName_eng { get; set; }
        public string RelationName_local { get; set; }
        public string Status { get; set; }
        public string Applicable_ForCCL { get; set; }
        public string Applicable_ForMaritalStatus { get; set; }
    }
}
