//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStateServiceGradingMaster
    {
        public string StateId { get; set; }
        public string deptid { get; set; }
        public int ServiceCd { get; set; }
        public int GradingCd { get; set; }
        public string GradingName { get; set; }
        public string GradingName_Local { get; set; }
        public string DeUserId { get; set; }
        public Nullable<System.DateTime> DeDate { get; set; }
        public string IpAddress { get; set; }
        public string LockedStatus { get; set; }
    }
}
