//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStateServiceMaster
    {
        public string StateId { get; set; }
        public string Deptid { get; set; }
        public int ServiceCd { get; set; }
        public string ServiceName { get; set; }
        public string ServiceName_Local { get; set; }
        public string ServiceAbbr { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IpAddress { get; set; }
        public string LockedStatus { get; set; }
    }
}
