//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstatemaster
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateName_Local { get; set; }
        public string StateAbbr { get; set; }
        public string CultureCode { get; set; }
        public string CultureName { get; set; }
        public string StateName_Culture { get; set; }
        public string LanguagePreferences { get; set; }
        public string StateMinisType { get; set; }
    }
}
