//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSubCategoryMaster
    {
        public int StateId { get; set; }
        public int SubCatId { get; set; }
        public string SubCatName { get; set; }
        public string SubCatName_local { get; set; }
        public string Status { get; set; }
    }
}
