//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msubquali_29_Dec_2020
    {
        public int code { get; set; }
        public string subcode { get; set; }
        public string name { get; set; }
        public string ncocode { get; set; }
        public string Status { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdationDate { get; set; }
        public string IP { get; set; }
    }
}
