//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisawarddetail
    {
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public long uniqid { get; set; }
        public System.DateTime dofaward { get; set; }
        public string awardtype { get; set; }
        public string awarddetail { get; set; }
        public Nullable<System.DateTime> updation_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string verify { get; set; }
        public string verified_by { get; set; }
        public string CIPAdress { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
    }
}
