//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempaddress
    {
        public Nullable<long> transid { get; set; }
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public string preaddress { get; set; }
        public string prestate { get; set; }
        public string predistt { get; set; }
        public string preblock { get; set; }
        public string pretown { get; set; }
        public string prepin { get; set; }
        public string prephone { get; set; }
        public string premobile { get; set; }
        public string email { get; set; }
        public string prePoliceStation { get; set; }
        public string preStreetNumber { get; set; }
        public string preMh_Vill { get; set; }
        public string preHouseNumber { get; set; }
        public string preWardNumber { get; set; }
        public string permaddr { get; set; }
        public string permstate { get; set; }
        public string permdistt { get; set; }
        public string permblock { get; set; }
        public string permtown { get; set; }
        public string permpin { get; set; }
        public string permphone { get; set; }
        public string permobile { get; set; }
        public string peremail { get; set; }
        public string perPoliceStation { get; set; }
        public string perStreetNumber { get; set; }
        public string perMh_Vill { get; set; }
        public string perHouseNumber { get; set; }
        public string perWardNumber { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Updated_By { get; set; }
        public string Verify { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string Verified_By { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
        public string IPAddress { get; set; }
    }
}
