//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempdepproceed
    {
        public string Stateid { get; set; }
        public long deptprocid { get; set; }
        public Nullable<long> transid { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public string ChargeStatus { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Updated_By { get; set; }
        public string Verify { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string Verified_By { get; set; }
        public string MPDpenaltyimposed { get; set; }
        public string MPDorderno { get; set; }
        public Nullable<System.DateTime> MPDdate { get; set; }
        public string DPD_PDorderno { get; set; }
        public Nullable<System.DateTime> DPD_PDorderdate { get; set; }
        public string DPD_PIfinancialyear { get; set; }
        public Nullable<System.DateTime> DPD_PIfromdate { get; set; }
        public Nullable<System.DateTime> DPD_PItodate { get; set; }
        public string DPD_FDfileno { get; set; }
        public string DPD_DelinquentEPdept { get; set; }
        public string DPD_DelinquentEPoffice { get; set; }
        public string DPD_DelinquentEPdesig { get; set; }
        public Nullable<System.DateTime> DPD_SReffdateofsus { get; set; }
        public string DPD_SRsusordno { get; set; }
        public Nullable<System.DateTime> DPD_SRsusdate { get; set; }
        public Nullable<System.DateTime> DPD_SReffdateofrev { get; set; }
        public string DPD_SRrevordno { get; set; }
        public Nullable<System.DateTime> DPD_SRrevdate { get; set; }
        public string DPD_CSordno { get; set; }
        public Nullable<System.DateTime> DPD_CSdate { get; set; }
        public Nullable<System.DateTime> DPD_CDappointmentdateofio { get; set; }
        public string DPD_CDinqoffordno { get; set; }
        public Nullable<System.DateTime> DPD_CDinqoffdate { get; set; }
        public string DPD_CDinqoffgpfno { get; set; }
        public string DPD_CDinqoffname { get; set; }
        public string DPD_CDinqoffdept { get; set; }
        public string DPD_CDinqoffdesig { get; set; }
        public Nullable<System.DateTime> DPD_CDappointmentdateofpo { get; set; }
        public string DPD_CDpreoffordno { get; set; }
        public Nullable<System.DateTime> DPD_CDpreoffdate { get; set; }
        public string DPD_CDpreoffgpfno { get; set; }
        public string DPD_CDpreoffname { get; set; }
        public string DPD_CDpreoffdept { get; set; }
        public string DPD_CDpreoffdesig { get; set; }
        public string DPD_RDreplacementof { get; set; }
        public string DPD_RDnameofreplacedoff { get; set; }
        public string DPD_RDdeptofreplacedoff { get; set; }
        public string DPD_RDdesigofreplacedoff { get; set; }
        public Nullable<System.DateTime> DPD_RDdateofappointment { get; set; }
        public string DPD_RDgpfnoofreplofficer { get; set; }
        public string DPD_RDnameofreplofficer { get; set; }
        public string DPD_RDdeptofreplofficer { get; set; }
        public string DPD_RDdesigofreplofficer { get; set; }
        public string DPD_RDordnoofrepl { get; set; }
        public Nullable<System.DateTime> DPD_RDorddateofrepl { get; set; }
        public string DPD_RDremarksofrepl { get; set; }
        public string DPS_CSIDcasestatus { get; set; }
        public string DPS_CSIDorderno { get; set; }
        public Nullable<System.DateTime> DPS_CSIDdate { get; set; }
        public string DPS_CSIDdisofpnlt { get; set; }
        public string DPS_CSIDpercentanddurationofpension { get; set; }
        public string DPS_AOappealbyofficer { get; set; }
        public string DPS_AOdept { get; set; }
        public string DPS_AOdesig { get; set; }
        public string DPS_AOoutcomeofapl { get; set; }
        public string DPS_AOordno { get; set; }
        public Nullable<System.DateTime> DPS_AOdate { get; set; }
        public string DPS_AOdisofpnlt { get; set; }
        public string DPS_AOpercentanddurationofpension { get; set; }
        public string CPD_CCDfirno { get; set; }
        public Nullable<System.DateTime> CPD_CCDfirdate { get; set; }
        public string CPD_CCDpolicevigcbi { get; set; }
        public string CPD_CCDpolicestationdistrict { get; set; }
        public string CPD_CCDnameofpolicestation { get; set; }
        public string CPD_CCDgrno { get; set; }
        public Nullable<System.DateTime> CPD_CCDgrdate { get; set; }
        public string CPD_PDprosecutionsanordno { get; set; }
        public Nullable<System.DateTime> CPD_PDprosecutionsandate { get; set; }
        public string CPD_PDdetailsoftrilcourt { get; set; }
        public Nullable<System.DateTime> CPChargeSheetDate { get; set; }
        public string CPD_CDcognizance { get; set; }
        public string CPD_OCPoutcomeofcriminalproceeding { get; set; }
        public string CPD_OCPdetailsOfPunishment { get; set; }
        public string LPCaseNo { get; set; }
        public string LPCaseYear { get; set; }
        public string LPCaseStatus { get; set; }
        public string LPrecommendation { get; set; }
        public string LPactiontknbydept { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
    }
}
