//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempnominee
    {
        public Nullable<long> transid { get; set; }
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public long uniqid { get; set; }
        public string nomtype { get; set; }
        public string nomname { get; set; }
        public string nomrelation { get; set; }
        public string nom_dob { get; set; }
        public Nullable<decimal> nompercen { get; set; }
        public string UID_No { get; set; }
        public string nom_bnkAcNo { get; set; }
        public string nom_BankName { get; set; }
        public string nom_BranchName { get; set; }
        public string nom_IFSCCode { get; set; }
        public string nom_minorstatus { get; set; }
        public string nom_guardianDetail { get; set; }
        public string nomaddress { get; set; }
        public string nomstreetNo { get; set; }
        public string nomMh_Vill { get; set; }
        public string nomHouseNo { get; set; }
        public string nomWardNo { get; set; }
        public string nomst { get; set; }
        public string nomdist { get; set; }
        public string nomblk { get; set; }
        public string nomtown { get; set; }
        public string nomPoliceStation { get; set; }
        public string nompincd { get; set; }
        public string nommobileno { get; set; }
        public string nomEmail { get; set; }
        public string nomphone { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Updated_By { get; set; }
        public string Verify { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string Verified_By { get; set; }
        public string CIPAdress { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
        public string remarks { get; set; }
        public string main_Alt_Nominee { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentExt { get; set; }
    }
}
