//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempeducation
    {
        public Nullable<long> transid { get; set; }
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public long uniqid { get; set; }
        public long eduid { get; set; }
        public string eduyear { get; set; }
        public string eduinst { get; set; }
        public string edustream { get; set; }
        public Nullable<long> edumark { get; set; }
        public string edugrade { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Updated_by { get; set; }
        public string Verify { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string Verified_By { get; set; }
        public string CIPAdress { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentExt { get; set; }
        public string remarks { get; set; }
        public string eduAcquringStatus { get; set; }
        public string RollNo_EnrolmentNo { get; set; }
    }
}
