//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempjoinrelievedetail
    {
        public byte StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public int joinid { get; set; }
        public string joindeptid { get; set; }
        public Nullable<long> joinofficeid { get; set; }
        public Nullable<int> joinreason { get; set; }
        public string joinonAForFN { get; set; }
        public Nullable<System.DateTime> joindt { get; set; }
        public string joinordernodt { get; set; }
        public Nullable<System.DateTime> joinorderdt { get; set; }
        public string joindesig { get; set; }
        public string joinSubDesig { get; set; }
        public string joinDeptName { get; set; }
        public Nullable<byte> joinOfficeStateId { get; set; }
        public Nullable<short> joinOfficeDistcd { get; set; }
        public string joinOfficeName { get; set; }
        public string joinDesigName { get; set; }
        public string areaasTribalhardsub { get; set; }
        public string whetherhomedist { get; set; }
        public Nullable<int> joinbranch { get; set; }
        public Nullable<int> joincadre { get; set; }
        public string joinclass { get; set; }
        public string JoinServiceCd { get; set; }
        public string JoinServiceGrading { get; set; }
        public string joinremarks { get; set; }
        public string joinemptype { get; set; }
        public string joingazngaz { get; set; }
        public string joinverify { get; set; }
        public byte[] J_OrderPDF { get; set; }
        public Nullable<int> relieveid { get; set; }
        public Nullable<System.DateTime> relievedt { get; set; }
        public string relieveaffn { get; set; }
        public string relievetranferorderno { get; set; }
        public Nullable<System.DateTime> relievetranferorderdt { get; set; }
        public string relievedeptid { get; set; }
        public string relieveofficeid { get; set; }
        public string relievedesig { get; set; }
        public string relievesubdesig { get; set; }
        public Nullable<int> relievebranch { get; set; }
        public string relieveremark { get; set; }
        public string relieveestabdeptid { get; set; }
        public string relieveestabofficeid { get; set; }
        public Nullable<int> relievefordesig { get; set; }
        public Nullable<int> relieveforsubdesig { get; set; }
        public string relieveestabDeptName { get; set; }
        public Nullable<byte> relieveestabOfficeStateId { get; set; }
        public Nullable<short> relieveestabOfficeDistcd { get; set; }
        public string relieveestabOfficeName { get; set; }
        public string relieveDesigName { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateondate { get; set; }
        public string relieveupdateby { get; set; }
        public Nullable<System.DateTime> relieveupdateondate { get; set; }
        public string IsAdditionalCharge { get; set; }
        public string relieveVerify { get; set; }
        public byte[] R_OrderPDF { get; set; }
        public string EntryStatus { get; set; }
        public string REntryStatus { get; set; }
        public string IsOnlineJoin { get; set; }
        public string IsJoinOrderOnline { get; set; }
        public string IsOnlineRelieve { get; set; }
        public string IsRelieveOrderOnline { get; set; }
        public string IsJoinPublished { get; set; }
        public string IsRelievedPublished { get; set; }
        public string JoinCopyTo { get; set; }
        public string JoinOrderBy { get; set; }
        public string RelieveCopyTo { get; set; }
        public string RelieveOrderBy { get; set; }
        public string IpAddress { get; set; }
        public string entitledJoinTime { get; set; }
        public string entitledJoinNoOfDays { get; set; }
        public string AvailedNoOfDays { get; set; }
        public string NotAvailedNoOfDays { get; set; }
        public Nullable<long> ReleivDesigid { get; set; }
        public Nullable<long> ReleivOfficerid { get; set; }
        public Nullable<long> SignDesigid { get; set; }
        public Nullable<long> SignOfficerid { get; set; }
        public string Authority_Deptid { get; set; }
        public string Authority_Code { get; set; }
        public Nullable<long> JoinDesigid { get; set; }
        public Nullable<long> JoinOfficerid { get; set; }
        public Nullable<long> JoinSignDesigid { get; set; }
        public Nullable<long> JoinSignOfficerid { get; set; }
    }
}
