//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempleave
    {
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public long uniqid { get; set; }
        public string leavetype { get; set; }
        public System.DateTime fromdt { get; set; }
        public System.DateTime todt { get; set; }
        public string reason { get; set; }
        public string ltcavail { get; set; }
        public string stationleave { get; set; }
        public string sanctofficer { get; set; }
        public string leavest { get; set; }
        public Nullable<long> leavbal { get; set; }
        public Nullable<long> leamlbal { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Updated_By { get; set; }
        public string Verify { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string Verified_By { get; set; }
        public string CIPAdress { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
        public Nullable<decimal> totalNoOfDays { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentExt { get; set; }
        public string LeaveNumerator { get; set; }
        public string LeaveDenominator { get; set; }
        public string LeaveTransBalance { get; set; }
        public string LeaveTransBalance_Numerator { get; set; }
        public string LeaveTransBalance_Denominator { get; set; }
    }
}
