//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Combined.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisempfamily
    {
        public Nullable<long> transid { get; set; }
        public int StateID { get; set; }
        public string deptid { get; set; }
        public string empcd { get; set; }
        public long uniqid { get; set; }
        public string memname { get; set; }
        public string memrelation { get; set; }
        public Nullable<System.DateTime> memdob { get; set; }
        public string memdepend { get; set; }
        public string memempstcent { get; set; }
        public string memempiph { get; set; }
        public string memdepname { get; set; }
        public string memiphempcd { get; set; }
        public string memesalarycd { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Updated_By { get; set; }
        public string Verify { get; set; }
        public Nullable<System.DateTime> dofvalid { get; set; }
        public string Verified_By { get; set; }
        public string CIPAdress { get; set; }
        public Nullable<long> VerifyGroupId { get; set; }
        public string MemberUIdNo { get; set; }
        public string memberEdu { get; set; }
        public string ActiveStatus { get; set; }
        public string InActiveReason { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentExt { get; set; }
    }
}
